# Generated by Django 5.0.4 on 2024-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_password_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bot_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграмм id пользователя'),
        ),
    ]
